# Generated by Django 5.0.2 on 2024-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.CharField(max_length=20)),
                ('fechaVencimiento', models.DateField()),
                ('fechaPago', models.DateField()),
                ('importePagar', models.FloatField()),
                ('importePagado', models.FloatField()),
                ('importeAdeudado', models.FloatField()),
            ],
        ),
    ]
