# Generated by Django 5.0.2 on 2024-02-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_remove_cuenta_importeadeudado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='importeAdeudado_db',
        ),
    ]
