# Generated by Django 5.0.2 on 2024-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_remove_cuenta_importeadeudado_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cantidadCuotas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
